# Generated by Django 6.0.8 on 2026-08-10 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(choices=[('EARRING', 'Brinco'), ('NECKLACE', 'Colar'), ('RING', 'Anel'), ('BRACELET', 'Pulseira'), ('ANKLET', 'Tornozeleira')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('ARCHIVED', 'Arquivado')], default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('REFERENCE', 'Referência')], default='ORIGINAL', max_length=20)),
                ('file', models.ImageField(upload_to='products/originals/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
