# Generated by Django 6.0.8 on 2026-08-10 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('reserved_balance', models.PositiveIntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PURCHASE', 'Compra'), ('BONUS', 'Bônus'), ('RESERVE', 'Reserva'), ('CONSUME', 'Consumo'), ('REFUND', 'Estorno'), ('ADJUSTMENT', 'Ajuste')], max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reserved_before', models.IntegerField(default=0)),
                ('reserved_after', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='studio.generation')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credits.creditwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
