# Generated by Django 6.0.8 on 2026-08-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='plan_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='plan_balance_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='plan_balance_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='plan_reserved_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='plan_reserved_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='purchased_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='purchased_balance_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='purchased_balance_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='purchased_reserved_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='purchased_reserved_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creditwallet',
            name='plan_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditwallet',
            name='plan_reserved_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditwallet',
            name='purchased_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditwallet',
            name='purchased_reserved_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='type',
            field=models.CharField(choices=[('PLAN_GRANT', 'Créditos do plano'), ('PLAN_EXPIRE', 'Expiração do plano'), ('PURCHASE', 'Compra avulsa'), ('BONUS', 'Bônus'), ('RESERVE', 'Reserva'), ('CONSUME', 'Consumo'), ('REFUND', 'Estorno'), ('ADJUSTMENT', 'Ajuste administrativo')], max_length=30),
        ),
    ]
