# Generated by Django 6.0.8 on 2026-09-15 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRecoveryQuestionChallenge',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('question_1_id', models.CharField(max_length=32)),
                ('question_2_id', models.CharField(max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_question_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRecoverySecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_key_hash', models.CharField(blank=True, max_length=128)),
                ('security_question_1', models.CharField(blank=True, max_length=255)),
                ('security_answer_1_hash', models.CharField(blank=True, max_length=128)),
                ('security_question_2', models.CharField(blank=True, max_length=255)),
                ('security_answer_2_hash', models.CharField(blank=True, max_length=128)),
                ('configured_at', models.DateTimeField(blank=True, null=True)),
                ('key_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account recovery security',
                'verbose_name_plural': 'account recovery securities',
            },
        ),
    ]
