# Generated by Codex for PAYMENT-002-FIX-003.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_subscription_last_processed_stripe_invoice_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionCheckoutAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATING", "Criando"),
                            ("OPEN", "Aberta"),
                            ("COMPLETED", "Concluída"),
                            ("EXPIRED", "Expirada"),
                            ("FAILED", "Falhou"),
                        ],
                        default="CREATING",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "stripe_checkout_url",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "stripe_idempotency_key",
                    models.CharField(
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "request_signature",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_checkout_attempts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_checkout_attempts",
                        to="billing.plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_attempts",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriptioncheckoutattempt",
            index=models.Index(
                fields=["organization", "plan", "status"],
                name="billing_co_attempt_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptioncheckoutattempt",
            index=models.Index(
                fields=["stripe_checkout_session_id"],
                name="billing_co_session_lookup",
            ),
        ),
    ]
