# Generated by Django 6.0.8 on 2026-09-01 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscriptioncheckoutattempt'),
        ('organizations', '0002_organization_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_price_signature', models.CharField(blank=True, max_length=80)),
                ('stripe_synced_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_sync_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_credit_limit_per_cycle',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Paga'), ('FAILED', 'Falhou'), ('CANCELED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=20)),
                ('credits_snapshot', models.PositiveIntegerField()),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_snapshot', models.CharField(max_length=3)),
                ('stripe_price_id_snapshot', models.CharField(max_length=255)),
                ('extra_credit_limit_snapshot', models.PositiveIntegerField(default=0)),
                ('cycle_start', models.DateTimeField()),
                ('cycle_end', models.DateTimeField()),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_checkout_url', models.TextField(blank=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_idempotency_key', models.CharField(max_length=255, unique=True)),
                ('request_signature', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('processed_event_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_purchases', to='organizations.organization')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='billing.creditpackage')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_purchases', to='billing.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_purchases', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'subscription', 'status', 'cycle_start', 'cycle_end'], name='billing_purchase_cycle'), models.Index(fields=['stripe_checkout_session_id'], name='billing_purchase_session'), models.Index(fields=['stripe_payment_intent_id'], name='billing_purchase_pi')],
            },
        ),
    ]
