from django.urls import path

from .views import (
    CreditAdjustmentView,
    SuperAdminAuditLogListView,
    SuperAdminClientActivateSubscriptionView,
    SuperAdminClientDetailView,
    SuperAdminClientListCreateView,
    SuperAdminCreditWalletListView,
    SuperAdminGenerationDetailView,
    SuperAdminGenerationListView,
    SuperAdminOrganizationDetailView,
    SuperAdminOrganizationListView,
    SuperAdminPlanDetailView,
    SuperAdminPlanListView,
    SuperAdminSceneTemplateDetailView,
    SuperAdminSceneTemplateListCreateView,
    SuperAdminSubscriptionDetailView,
    SuperAdminSubscriptionListView,
    SuperAdminSubscriptionRenewView,
    SuperAdminSummaryView,
    SuperAdminUserDetailView,
    SuperAdminUserListView,
)


app_name = "superadmin"


urlpatterns = [
    path(
        "summary/",
        SuperAdminSummaryView.as_view(),
        name="summary",
    ),
    path(
        "audit-logs/",
        SuperAdminAuditLogListView.as_view(),
        name="audit-logs",
    ),
    path(
        "clients/",
        SuperAdminClientListCreateView.as_view(),
        name="clients",
    ),
    path(
        "clients/<uuid:pk>/",
        SuperAdminClientDetailView.as_view(),
        name="client-detail",
    ),
    path(
        "clients/<uuid:pk>/activate-subscription/",
        SuperAdminClientActivateSubscriptionView.as_view(),
        name="client-activate-subscription",
    ),
    path(
        "organizations/",
        SuperAdminOrganizationListView.as_view(),
        name="organizations",
    ),
    path(
        "organizations/<uuid:pk>/",
        SuperAdminOrganizationDetailView.as_view(),
        name="organization-detail",
    ),
    path(
        "accounts/",
        SuperAdminUserListView.as_view(),
        name="accounts",
    ),
    path(
        "accounts/<int:pk>/",
        SuperAdminUserDetailView.as_view(),
        name="account-detail",
    ),
    path(
        "plans/",
        SuperAdminPlanListView.as_view(),
        name="plans",
    ),
    path(
        "plans/<uuid:pk>/",
        SuperAdminPlanDetailView.as_view(),
        name="plan-detail",
    ),
    path(
        "subscriptions/",
        SuperAdminSubscriptionListView.as_view(),
        name="subscriptions",
    ),
    path(
        "subscriptions/<uuid:pk>/",
        SuperAdminSubscriptionDetailView.as_view(),
        name="subscription-detail",
    ),
    path(
        "subscriptions/<uuid:pk>/renew/",
        SuperAdminSubscriptionRenewView.as_view(),
        name="subscription-renew",
    ),
    path(
        "credit-wallets/",
        SuperAdminCreditWalletListView.as_view(),
        name="credit-wallets",
    ),
    path(
        "generations/",
        SuperAdminGenerationListView.as_view(),
        name="generations",
    ),
    path(
        "generations/<uuid:pk>/",
        SuperAdminGenerationDetailView.as_view(),
        name="generation-detail",
    ),
    path(
        "scene-templates/",
        SuperAdminSceneTemplateListCreateView.as_view(),
        name="scene-templates",
    ),
    path(
        "scene-templates/<uuid:pk>/",
        SuperAdminSceneTemplateDetailView.as_view(),
        name="scene-template-detail",
    ),
    path(
        "credit-adjustments/",
        CreditAdjustmentView.as_view(),
        name="credit-adjustments",
    ),
]
