# Generated by Django 6.0.8 on 2026-08-10 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, help_text='Vazio = regra universal', max_length=20)),
                ('rule_type', models.CharField(max_length=80)),
                ('instruction', models.TextField()),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('INSTAGRAM', 'Instagramável'), ('MODEL', 'Modelo'), ('BODY_DETAIL', 'Detalhe no Corpo'), ('STILL', 'Still')], max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Criada'), ('CREDIT_RESERVED', 'Crédito reservado'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada')], default='CREATED', max_length=24)),
                ('failure_type', models.CharField(blank=True, choices=[('TECHNICAL', 'Técnica'), ('VALIDATION', 'Validação'), ('PROVIDER', 'Provedor'), ('CONTENT', 'Conteúdo'), ('UNKNOWN', 'Desconhecida')], max_length=20)),
                ('provider', models.CharField(default='OPENAI', max_length=40)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('final_prompt', models.TextField(blank=True)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('api_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('credit_cost', models.PositiveIntegerField(default=1)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='generations/%Y/%m/')),
                ('mime_type', models.CharField(default='image/png', max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('generation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_image', to='studio.generation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=20)),
                ('generation_mode', models.CharField(choices=[('INSTAGRAM', 'Instagramável'), ('MODEL', 'Modelo'), ('BODY_DETAIL', 'Detalhe no Corpo'), ('STILL', 'Still')], max_length=20)),
                ('body_area', models.CharField(blank=True, max_length=80)),
                ('framing', models.CharField(max_length=80)),
                ('product_priority', models.CharField(default='MAXIMUM', max_length=20)),
                ('body_priority', models.CharField(default='MEDIUM', max_length=20)),
                ('background_priority', models.CharField(default='LOW', max_length=20)),
                ('product_visibility', models.CharField(default='FULL', max_length=20)),
                ('detail_level', models.CharField(default='MAXIMUM', max_length=20)),
                ('placement_instruction', models.TextField(blank=True)),
                ('additional_rules', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'generation_mode'), name='uniq_generation_rule')],
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='generation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='studio.generationrule'),
        ),
        migrations.CreateModel(
            name='SceneTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('generation_mode', models.CharField(choices=[('INSTAGRAM', 'Instagramável'), ('MODEL', 'Modelo'), ('BODY_DETAIL', 'Detalhe no Corpo'), ('STILL', 'Still')], max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/')),
                ('prompt_template', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('slug', 'generation_mode', 'category', 'version'), name='uniq_template_version')],
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='scene_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='studio.scenetemplate'),
        ),
        migrations.AddConstraint(
            model_name='generation',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_generation_idempotency'),
        ),
    ]
