# Generated by Django 6.0.8 on 2026-08-17 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_seed_initial_model_references'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='model_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='ai.modelreference'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='mode',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagramável'), ('MODEL', 'Na Modelo'), ('BODY_DETAIL', 'Detalhe no Corpo'), ('STILL', 'Still')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generationrule',
            name='generation_mode',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagramável'), ('MODEL', 'Na Modelo'), ('BODY_DETAIL', 'Detalhe no Corpo'), ('STILL', 'Still')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scenetemplate',
            name='generation_mode',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagramável'), ('MODEL', 'Na Modelo'), ('BODY_DETAIL', 'Detalhe no Corpo'), ('STILL', 'Still')], max_length=20),
        ),
    ]
